[package]
name = "multi_coins_wallet_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { path = "../../../../../keystore", default-features = false }
app_wallets = { path = "../../../../../apps/wallets" }
third_party = { path = "../../../../../third_party" }
app_utils = { path = "../../../../../apps/utils" }
rust_tools = {path="../../../../../tools"}
app_arweave = {path = "../../../../../apps/arweave"}
cty = "0.2.2"
cstr_core = "0.2.6"

common_rust_c = {path = "../../../common"}

[features]
default = ["multi-coins"]
multi-coins = []
btc-only = []